load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "debug_proto",
    srcs = [
        "debug.proto",
        "nsf_debug_data.proto",
        "port_debug_data.proto",
    ],
    visibility = ["//visibility:public"],
    deps = ["@com_google_protobuf//:timestamp_proto"],
)

go_proto_library(
    name = "debug_go_proto",
    # Note: go_grpc_v2 only generates stubs, not message types.
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],  # keep
    importpath = "github.com/sonic-net/sonic-gnmi/proto/gnoi/debug",
    proto = ":debug_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "debug",
    embed = [":debug_go_proto"],
    importpath = "github.com/sonic-net/sonic-gnmi/proto/gnoi/debug",
    visibility = ["//visibility:public"],
)

alias(
    name = "go_default_library",
    actual = ":debug",
    visibility = ["//visibility:public"],
)
