load("@io_bazel_rules_go//go:def.bzl", "go_library")

#gazelle:exclude empty.go

# This target looks to gazelle like it's not imported from anywhere,
# but we need it to include the swsscommon C library.
#keep
go_library(
    name = "swsscommon",
    srcs = ["empty.go"],
    embed = ["@sonic-swss-common//goext:swsscommon"],
    importpath = "github.com/sonic-net/sonic-gnmi/swsscommon",
    visibility = ["//visibility:public"],
)

# cc_library(
#     name = "swsscommon_go_cpp",
#     srcs = [
#         "swsscommon_wrap.cxx",
#     ],
#     hdrs = ["swsscommon_wrap.h"],
#     copts = ["-Iexternal/sonic-swss-common/common"],
#     deps = [
#         "@com_github_cesnet_libyang//:libyang",
#         "@sonic-swss-common//:swsscommon_base",
#     ],
# )
#
# alias(
#     name = "go_default_library",
#     actual = ":swsscommon",
#     visibility = ["//visibility:public"],
# )
